### ISSUE TITLE
Tags collection and add/remove?

### ISSUE THREAD

**Issue by jdshkolnik** [tfsaggregator/tfsaggregator-core#9]
Hi,

1. Is there a way to add/remove tags from a work item?
2. Is it possible to test for existence of a particular tag? ex: `If self.Tags.Contains("SomeTag")...`

**Comment by jessehouwing** [comment]
1. The old client object model has always been particular about tags. This
will be possible once we switch to the new rest based api.
2. self.Fields["System.Tags"].Value.Split should do wonders.
